import {useEffect,useMemo,useState} from "react";
import {Check,Printer,Plus} from "lucide-react";
import {db} from "../lib/supabase"; import {useHRAuth} from "../lib/auth";
import {collection,getDocs,query,where,addDoc,doc,setDoc} from "firebase/firestore";
type C={id:string;code:string;name:string;course:string;teacher:string;teacherUserId:string|null;branch:string;center:string;schedule:string;totalSessions:number;status:string};
type S={id:string;code:string;name:string;phone:string;classId:string;startDate:string}; type Se={id:string;classId:string;no:number;date:string;topic:string}; type M={id?:string;sessionId:string;studentId:string;attendance:string;homework:boolean;reason:string;noteDate:string};
const demo:C[]=[{id:"C001",code:"LH-TQ-01",name:"Tiếng Trung giao tiếp cơ bản",course:"Giao tiếp",teacher:"Giáo viên tiếng Trung",teacherUserId:null,branch:"Bắc Ninh",center:"Bắc Ninh",schedule:"2-4-6 • 19:30–21:00",totalSessions:30,status:"Đang học"},{id:"C002",code:"HSK2-01",name:"HSK 0 → HSK2 4 kỹ năng",course:"HSK 3.0",teacher:"Giáo viên tiếng Trung",teacherUserId:null,branch:"Lạng Sơn",center:"Lạng Sơn",schedule:"3-5-7 • 19:30–21:00",totalSessions:45,status:"Đang học"}];
const today=new Date().toISOString().slice(0,10);
export default function ClassAttendance(){
 const {profile,session}=useHRAuth(); const live=Boolean(db&&session); const [classes,setClasses]=useState<C[]>(live?[]:demo),[students,setStudents]=useState<S[]>([]),[sessions,setSessions]=useState<Se[]>([]),[marks,setMarks]=useState<M[]>([]),[selected,setSelected]=useState(""),[month,setMonth]=useState(today.slice(0,7)),[showC,setShowC]=useState(false),[showS,setShowS]=useState(false),[q,setQ]=useState(""),[saving,setSaving]=useState(false);
 const room=classes.find(c=>c.id===selected)||classes[0];
 const roomStudents=useMemo(()=>students.filter(s=>s.classId===room?.id&&(${s.name}${s.code}${s.phone}).toLowerCase().includes(q.toLowerCase())),[students,room,q]);
 const monthSessions=useMemo(()=>sessions.filter(s=>s.classId===room?.id&&s.date.slice(0,7)===month).sort((a,b)=>a.date.localeCompare(b.date)),[sessions,room,month]);
 async function load(){if(!db)return;const base=profile?.role==="branch_director"?query(collection(db,"classes"),where("branch","==",profile.branch)):profile?.role==="center_director"?query(collection(db,"classes"),where("center","==",profile.center)):profile?.role?.startsWith("teacher_")?query(collection(db,"classes"),where("teacher_user_id","==",session?.uid)):query(collection(db,"classes"));const cs=await getDocs(base);const arr=cs.docs.map(d=>({id:d.id,...d.data()} as C));setClasses(arr);if(!selected&&arr[0])setSelected(arr[0].id)}
 useEffect(()=>{if(live)load()},[live,profile?.user_id]);
 async function loadRoom(){if(!db||!room)return;const [ss,se]=await Promise.all([getDocs(query(collection(db,"students"),where("class_id","==",room.id))),getDocs(query(collection(db,"sessions"),where("class_id","==",room.id)))]);setStudents(ss.docs.map(d=>({id:d.id,...d.data()} as S)));const ses=se.docs.map(d=>({id:d.id,...d.data()} as Se));setSessions(ses);if(ses.length){const at=await getDocs(query(collection(db,"classAttendance"),where("class_id","==",room.id)));setMarks(at.docs.map(d=>({id:d.id,...d.data()} as M)))}}
 useEffect(()=>{if(live&&room)loadRoom()},[live,room?.id]);
 function dates(){if(!room)return[];const [y,m]=month.split("-").map(Number),last=new Date(y,m,0).getDate(),wanted=room.schedule.includes("2-4-6")?[1,3,5]:room.schedule.includes("3-5-7")?[2,4,6]:[1,2,3,4,5,6];return Array.from({length:last},(_,i)=>i+1).filter(d=>wanted.includes(new Date(y,m-1,d).getDay())).map(d=>month+"-"+String(d).padStart(2,"0"))}
 async function createSessions(){if(!room)return;setSaving(true);const existing=new Set(monthSessions.map(x=>x.date));let n=sessions.filter(x=>x.classId===room.id).length;for(const date of dates().filter(x=>!existing.has(x))){n++;const data={class_id:room.id,session_no:n,session_date:date,topic:""};if(db)await addDoc(collection(db,"sessions"),data);else setSessions(x=>[...x,{id:crypto.randomUUID(),classId:room.id,no:n,date,topic:""}])}if(live)await loadRoom();setSaving(false)}
 async function mark(se:Se,st:S,status:string,homework?:boolean){const old=marks.find(x=>x.sessionId===se.id&&x.studentId===st.id),data={class_id:room?.id,session_id:se.id,student_id:st.id,status:status||old?.attendance||"Có mặt",homework:homework??old?.homework??false,reason:old?.reason||"",note_date:old?.noteDate||""};setSaving(true);if(db){const id=old?.id||se.id+"_"+st.id;await setDoc(doc(db,"classAttendance",id),data,{merge:true});setMarks(x=>[...x.filter(m=>m.id!==id),{id,...data,attendance:data.status,sessionId:se.id,studentId:st.id,homework:data.homework,reason:data.reason,noteDate:data.note_date} as M])}else setMarks(x=>[...x.filter(m=>!(m.sessionId===se.id&&m.studentId===st.id)),{...data,sessionId:se.id,studentId:st.id,attendance:data.status,noteDate:data.note_date} as M]);setSaving(false)}
 async function addClass(){const data={code:formC.code,name:formC.name,course:formC.course,teacher:formC.teacher,teacher_user_id:formC.teacherUserId||null,branch:formC.branch,center:formC.center,schedule:formC.schedule,total_sessions:Number(formC.totalSessions),status:"Đang học"};if(db){const r=await addDoc(collection(db,"classes"),data);setSelected(r.id);await load()}else{const id=crypto.randomUUID();setClasses(x=>[...x,{id,...data,teacherUserId:data.teacher_user_id} as C]);setSelected(id)}setShowC(false)}
 async function addStudent(){if(!room)return;const data={class_id:room.id,student_code:formS.code,full_name:formS.name,phone:formS.phone,start_date:formS.startDate};if(db)await addDoc(collection(db,"students"),data);else setStudents(x=>[...x,{id:crypto.randomUUID(),classId:room.id,code:data.student_code,name:data.full_name,phone:data.phone,startDate:data.start_date}]);if(live)await loadRoom();setShowS(false)}
 const [formC,setFormC]=useState({code:"",name:"",course:"HSK 3.0",teacher:"",teacherUserId:"",branch:"Bắc Ninh",center:"Bắc Ninh",schedule:"2-4-6 • 19:30–21:00",totalSessions:30}); const [formS,setFormS]=useState({code:"",name:"",phone:"",startDate:today});
 const get=(se:string,st:string)=>marks.find(x=>x.sessionId===se&&x.studentId===st); const canManage=!!profile&&["company_director","admin","branch_director","center_director"].includes(profile.role);
 return <div className="attendance-sheet-wrap"><div className="toolbar no-print" style={{justifyContent:"space-between",flexWrap:"wrap"}}><div style={{display:"flex",gap:8}}><select className="select" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Chọn lớp</option>{classes.map(c=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</select><input className="input" style={{width:110}} type="month" value={month} onChange={e=>setMonth(e.target.value)}/><input className="input" placeholder="Tìm học viên" value={q} onChange={e=>setQ(e.target.value)}/></div><div style={{display:"flex",gap:8}}>{(canManage||!live)&&<><button className="btn gray" onClick={createSessions}><Plus size={14}/> Tạo lịch buổi</button><button className="btn gray" onClick={()=>setShowS(true)}><Plus size={14}/> Học viên</button><button className="btn gray" onClick={()=>setShowC(true)}><Plus size={14}/> Tạo lớp</button></>}<button className="btn" onClick={()=>window.print()}><Printer size={14}/> In</button></div></div>
 {room&&<div className="attendance-paper"><div className="attendance-title">ATTENDANCE – PHIẾU ĐIỂM DANH</div><div className="attendance-month">THÁNG {month.slice(5)}/{month.slice(0,4)}</div><div className="class-info"><b>{room.code} — {room.name}</b><div>{room.course} • {room.branch} • {room.schedule}</div><div>{monthSessions.length} buổi {saving&&"• Đang lưu…"}</div></div><div className="sheet-scroll"><table className="attendance-table"><thead><tr><th>STT</th><th>Student Name</th><th>Starting date</th>{monthSessions.map(s=><th key={s.id}>{s.date.slice(8)}<br/><small>{s.no}</small></th>)}</tr></thead><tbody>{roomStudents.map((st,i)=><tr key={st.id}><td>{i+1}</td><td><b>{st.name}</b><small>{st.code}</small></td><td>{st.startDate}</td>{monthSessions.map(se=>{const x=get(se.id,st.id);return <td key={se.id}><select value={x?.attendance||""} onChange={e=>mark(se,st,e.target.value)}><option value="">—</option><option value="Có mặt">P</option><option value="Đi muộn">L</option><option value="Vắng">A</option><option value="Nghỉ phép">E</option></select><button className={"hw-check "+(x?.homework?"done":"")} onClick={()=>mark(se,st,x?.attendance||"Có mặt",!x?.homework)}>{x?.homework?<Check size={12}/>:null}</button></td>})}</tr>)}</tbody></table></div><div className="sheet-summary">Tổng học viên: <b>{roomStudents.length}</b> • Tổng buổi: <b>{monthSessions.length}</b></div><div className="confirmation">Xác nhận sau mỗi buổi học — Giáo viên ký: __________________</div></div>}
 {showC&&<div className="modal no-print"><div className="modalbox"><h2>Tạo lớp</h2><div className="form">{Object.entries(formC).filter(([k])=>k!=="teacherUserId").map(([k,v])=><label key={k}>{k}<input className="input" value={String(v)} onChange={e=>setFormC({...formC,[k]:k==="totalSessions"?Number(e.target.value):e.target.value})}/></label>)}</div><div className="actions"><button className="btn gray" onClick={()=>setShowC(false)}>Hủy</button><button className="btn" onClick={addClass}>Lưu</button></div></div></div>}
 {showS&&<div className="modal no-print"><div className="modalbox"><h2>Thêm học viên</h2><div className="form">{Object.entries(formS).map(([k,v])=><label key={k}>{k}<input className="input" value={v} onChange={e=>setFormS({...formS,[k]:e.target.value})}/></label>)}</div><div className="actions"><button className="btn gray" onClick={()=>setShowS(false)}>Hủy</button><button className="btn" onClick={addStudent}>Thêm</button></div></div></div>}</div>
}
