import {useMemo,useState} from "react";
import {Users,Clock3,CalendarDays,Building2,LayoutDashboard,Network,BriefcaseBusiness,Plus,LogIn,LogOut,Search} from "lucide-react";

type Emp={id:string;name:string;role:string;dept:string;branch:string;center:string;status:"Đang làm"|"Tạm nghỉ"|"Nghỉ việc";specialty:string;join:string};
type Att={id:string;date:string;employee:string;in?:string;out?:string;hours?:number;status:string};
const seed:Emp[]=[
{id:"LH001",name:"Nguyễn Minh Anh",role:"Giám đốc công ty",dept:"Ban Giám đốc",branch:"Toàn công ty",center:"Trụ sở",status:"Đang làm",specialty:"Quản trị",join:"2025-01-01"},
{id:"LH002",name:"Trần Quốc Nam",role:"Giám đốc chi nhánh",dept:"Ban Giám đốc",branch:"Lạng Sơn",center:"Lạng Sơn",status:"Đang làm",specialty:"Điều hành",join:"2025-03-01"},
{id:"LH003",name:"Lê Thu Hà",role:"Giám đốc trung tâm",dept:"Điều hành",branch:"Bắc Ninh",center:"Bắc Ninh",status:"Đang làm",specialty:"Đào tạo",join:"2025-04-10"},
{id:"LH004",name:"Phạm Ngọc Mai",role:"MKT",dept:"Marketing",branch:"Lạng Sơn",center:"Lạng Sơn",status:"Đang làm",specialty:"Digital Marketing",join:"2026-05-05"},
{id:"LH005",name:"Vũ Đức Thành",role:"Sale",dept:"Kinh doanh",branch:"Bắc Ninh",center:"Bắc Ninh",status:"Đang làm",specialty:"Tư vấn khóa học",join:"2026-06-12"},
{id:"LH006",name:"Hoàng Linh",role:"Giáo viên tiếng Trung",dept:"Giảng dạy",branch:"Lạng Sơn",center:"Lạng Sơn",status:"Đang làm",specialty:"HSK 1-6",join:"2026-07-01"},
{id:"LH007",name:"Nguyễn Lan",role:"Giáo viên tiếng Anh",dept:"Giảng dạy",branch:"Bắc Ninh",center:"Bắc Ninh",status:"Đang làm",specialty:"IELTS/TOEIC",join:"2026-07-15"},
{id:"LH008",name:"Kim Hương",role:"Giáo viên tiếng Hàn",dept:"Giảng dạy",branch:"Lạng Sơn",center:"Lạng Sơn",status:"Đang làm",specialty:"TOPIK",join:"2026-08-01"}
];
const today=new Date().toISOString().slice(0,10);
const load=<T,>(k:string,d:T):T=>{try{return JSON.parse(localStorage.getItem(k)||"null")??d}catch{return d}};
export default function App(){
 const [tab,setTab]=useState("dashboard");
 const [employees,setEmployees]=useState<Emp[]>(()=>load("lh_employees",seed));
 const [attendance,setAttendance]=useState<Att[]>(()=>load("lh_attendance",[]));
 const [query,setQuery]=useState(""); const [show,setShow]=useState(false);
 const [form,setForm]=useState<Emp>({id:"",name:"",role:"MKT",dept:"Marketing",branch:"Lạng Sơn",center:"Lạng Sơn",status:"Đang làm",specialty:"",join:today});
 const saveEmp=(list:Emp[])=>{setEmployees(list);localStorage.setItem("lh_employees",JSON.stringify(list))};
 const saveAtt=(list:Att[])=>{setAttendance(list);localStorage.setItem("lh_attendance",JSON.stringify(list))};
 const checkIn=(e:Emp)=>{const exists=attendance.find(a=>a.employee===e.id&&a.date===today);if(exists)return;saveAtt([...attendance,{id:e.id+"-"+today,date:today,employee:e.id,in:new Date().toLocaleTimeString("vi-VN",{hour:"2-digit",minute:"2-digit"}),status:"Đang làm"}])};
 const checkOut=(e:Emp)=>{const list=attendance.map(a=>{if(a.employee!==e.id||a.date!==today||!a.in||a.out)return a;const [h,m]=a.in.split(":").map(Number),now=new Date(),mins=now.getHours()*60+now.getMinutes()-(h*60+m),hours=Math.max(0,Math.round(mins/60*100)/100);return {...a,out:now.toLocaleTimeString("vi-VN",{hour:"2-digit",minute:"2-digit"}),hours,status:"Đã hoàn thành"}});saveAtt(list)};
 const checked=attendance.filter(a=>a.date===today);
 const stats={total:employees.length,active:employees.filter(e=>e.status==="Đang làm").length,checked:checked.length,missing:Math.max(0,employees.filter(e=>e.status==="Đang làm").length-checked.length)};
 const filtered=useMemo(()=>employees.filter(e=>(e.name+e.id+e.role+e.branch).toLowerCase().includes(query.toLowerCase())),[employees,query]);
 const nav=[["dashboard","Tổng quan",LayoutDashboard],["employees","Nhân viên",Users],["attendance","Chấm công",Clock3],["schedule","Lịch làm việc",CalendarDays],["leave","Nghỉ phép",BriefcaseBusiness],["org","Sơ đồ tổ chức",Network],["branches","Chi nhánh & trung tâm",Building2]];
 return <div className="app"><aside className="side"><div className="brand">LIÊN HOA<small>CONNECT • HR & CRM</small></div><div className="nav">{nav.map(([id,label,I]:any)=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}><I size={16} style={{verticalAlign:"middle",marginRight:9}}/>{label}</button>)}</div><div style={{position:"absolute",bottom:22,color:"#9ca3af",fontSize:11}}>Liên Hoa Global Education</div></aside><main className="main">
 <div className="top"><div><div className="title">{nav.find(x=>x[0]===tab)?.[1]}</div><div className="sub">Quản lý nhân sự • ngày {new Date().toLocaleDateString("vi-VN")}</div></div><button className="btn" onClick={()=>{setForm({...form,id:"LH"+String(employees.length+1).padStart(3,"0")});setShow(true)}}><Plus size={15}/> Thêm nhân viên</button></div>
 {tab==="dashboard"&&<><div className="cards">{[["Tổng nhân sự",stats.total],["Đang làm",stats.active],["Đã chấm công",stats.checked],["Chưa chấm công",stats.missing]].map(x=><div className="card" key={x[0] as string}><div className="muted">{x[0]}</div><div className="metric">{x[1]}</div></div>)}</div><div className="grid"><div className="card"><h3>Chấm công hôm nay</h3><table className="table"><thead><tr><th>Nhân viên</th><th>Giờ vào</th><th>Giờ ra</th><th>Trạng thái</th></tr></thead><tbody>{employees.filter(e=>e.status==="Đang làm").map(e=>{const a=checked.find(x=>x.employee===e.id);return <tr key={e.id}><td><b>{e.name}</b><div className="muted">{e.role} • {e.branch}</div></td><td>{a?.in||"—"}</td><td>{a?.out||"—"}</td><td><span className={"badge "+(a?.out?"ok":a?.in?"warn":"danger")}>{a?.status||"Chưa chấm công"}</span></td></tr>})}</tbody></table></div><div className="card"><h3>Phân bổ nhân sự</h3>{["MKT","Sale","Giáo viên tiếng Trung","Giáo viên tiếng Anh","Giáo viên tiếng Hàn"].map(r=><p key={r}>{r}<b style={{float:"right"}}>{employees.filter(e=>e.role===r).length}</b></p>)}</div></div></>}
 {tab==="employees"&&<><div className="toolbar"><div style={{position:"relative"}}><Search size={16} style={{position:"absolute",left:10,top:11}}/><input className="input" style={{paddingLeft:34,width:300}} placeholder="Tìm tên, mã, chức danh..." value={query} onChange={e=>setQuery(e.target.value)}/></div></div><table className="table"><thead><tr><th>Mã</th><th>Nhân viên</th><th>Chức danh</th><th>Cơ sở</th><th>Chuyên môn</th><th>Trạng thái</th></tr></thead><tbody>{filtered.map(e=><tr key={e.id}><td>{e.id}</td><td><b>{e.name}</b><div className="muted">{e.join}</div></td><td>{e.role}</td><td>{e.branch}</td><td>{e.specialty}</td><td><span className="badge ok">{e.status}</span></td></tr>)}</tbody></table></>}
 {tab==="attendance"&&<><div className="card" style={{marginBottom:16}}><h3>Chấm công hôm nay</h3><p className="muted">Ca mặc định: 08:00–17:30 • nghỉ 60 phút • dung sai 10 phút</p>{employees.filter(e=>e.status==="Đang làm").map(e=>{const a=checked.find(x=>x.employee===e.id);return <div key={e.id} style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"12px 0",borderTop:"1px solid #eee"}}><div><b>{e.name}</b><div className="muted">{e.role} • {e.branch}</div></div><div>{a?.in&&<span className="badge ok" style={{marginRight:8}}>Vào {a.in}</span>}{a?.out&&<span className="badge ok">Ra {a.out}</span>}{!a?.in&&<button className="btn" onClick={()=>checkIn(e)}><LogIn size={14}/> Bắt đầu ca</button>}{a?.in&&!a?.out&&<button className="btn gray" onClick={()=>checkOut(e)} style={{marginLeft:8}}><LogOut size={14}/> Kết thúc ca</button>}</div></div>})}</div></>}
 {tab==="org"&&<div className="card"><h3>Sơ đồ tổ chức</h3><div style={{padding:16,borderLeft:"3px solid #2563eb"}}><b>GIÁM ĐỐC CÔNG TY</b><div style={{marginLeft:24,marginTop:15}}><p>└─ <b>GIÁM ĐỐC CHI NHÁNH</b></p><div style={{marginLeft:24}}><p>├─ Lạng Sơn → Giám đốc trung tâm</p><p>└─ Bắc Ninh → Giám đốc trung tâm</p></div><p>└─ <b>Phòng Marketing / Sale / Giảng dạy</b></p></div></div></div>}
 {tab==="schedule"&&<div className="card"><h3>Lịch làm việc</h3><p>Quản lý ca 08:00–17:30 và lịch giảng dạy theo nhân viên. Có thể mở rộng phân ca theo ngày/tuần.</p><table className="table"><thead><tr><th>Nhân viên</th><th>Cơ sở</th><th>Ca</th><th>Ngày làm</th></tr></thead><tbody>{employees.map(e=><tr key={e.id}><td>{e.name}</td><td>{e.branch}</td><td>08:00–17:30</td><td>Thứ 2–Thứ 7</td></tr>)}</tbody></table></div>}
 {tab==="leave"&&<div className="card"><h3>Nghỉ phép / vắng mặt</h3><p className="muted">Theo dõi đơn nghỉ, lý do và trạng thái duyệt.</p><div className="card" style={{background:"#f8fafc"}}>Chưa có đơn nghỉ phép. Nút tạo đơn sẽ được kết nối với quy trình duyệt theo cấp quản lý.</div></div>}
 {tab==="branches"&&<div className="cards"><div className="card"><Building2/><h3>Chi nhánh Lạng Sơn</h3><div className="metric">{employees.filter(e=>e.branch==="Lạng Sơn").length}</div><div className="muted">nhân sự</div></div><div className="card"><Building2/><h3>Chi nhánh Bắc Ninh</h3><div className="metric">{employees.filter(e=>e.branch==="Bắc Ninh").length}</div><div className="muted">nhân sự</div></div></div>}
 {show&&<div className="modal"><div className="modalbox"><h2>Thêm nhân viên</h2><div className="form">{[["id","Mã nhân viên"],["name","Họ tên"],["specialty","Chuyên môn"],["join","Ngày vào làm"]].map(([k,l])=><label key={k}>{l}<input className="input" value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label>Chức danh<select className="select" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{["Giám đốc chi nhánh","Giám đốc trung tâm","MKT","Sale","Giáo viên tiếng Trung","Giáo viên tiếng Anh","Giáo viên tiếng Hàn"].map(x=><option key={x}>{x}</option>)}</select></label><label>Cơ sở<select className="select" value={form.branch} onChange={e=>setForm({...form,branch:e.target.value,center:e.target.value})}><option>Lạng Sơn</option><option>Bắc Ninh</option></select></label></div><div className="actions"><button className="btn gray" onClick={()=>setShow(false)}>Hủy</button><button className="btn" onClick={()=>{saveEmp([...employees,form]);setShow(false)}}>Lưu nhân viên</button></div></div></div>}
 </main></div>
}